# Generated by Django 3.1.12 on 2025-01-25 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('courierOutType', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('createdDate', models.DateField(blank=True, null=True)),
                ('lrUpdateDate', models.DateField()),
                ('voucherCodeId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('voucherCode', models.CharField(max_length=100)),
                ('voucherNo', models.IntegerField()),
                ('partyId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('partyName', models.CharField(max_length=255)),
                ('partyGroupCode', models.CharField(max_length=100)),
                ('courierNameId', models.UUIDField(blank=True, null=True)),
                ('courierName', models.CharField(blank=True, max_length=255, null=True)),
                ('courierNameAsRemark', models.CharField(blank=True, max_length=255, null=True)),
                ('saleBillId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('saleBillNo', models.CharField(max_length=100)),
                ('saleType', models.CharField(max_length=100)),
                ('courierNo', models.CharField(max_length=100)),
                ('courierNoDate', models.DateField()),
                ('documentType', models.CharField(max_length=100)),
                ('courierCharges', models.FloatField(blank=True, null=True)),
                ('paymentStatus', models.BooleanField(default=False)),
                ('stationName', models.CharField(max_length=255)),
                ('stateName', models.CharField(max_length=255)),
                ('pinCode', models.CharField(max_length=10)),
                ('remark', models.TextField(blank=True, null=True)),
                ('createdBy', models.CharField(max_length=255)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('deletedStatus', models.BooleanField(default=False)),
            ],
        ),
    ]
